apiVersion: v1
kind: Service
metadata:
  name: nexadesk-api-staging
spec:
  selector:
    app: nexadesk-api-staging
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP